#!/usr/bin/env ruby
# frozen_string_literal: true
#
# Quick-start launcher for reline-dialog-transform.
#
# - Verifies the active bundle has apple_sdk_mac + translation_mac-locale
#   (the demo can't show anything interesting without them) and aborts
#   early with a clear how-to-fix message when either is missing.
# - Generates a temporary isolated HOME with the dotfile + .irbrc so
#   your real ~/.irbrc is never touched.
# - Prints copy-pasteable instructions for what to type at the prompt.
# - Spawns `bundle exec irb` against the scratch HOME.
# - Cleans up the scratch HOME file-by-file with File.delete +
#   Dir.rmdir (no rm -rf, ever; rmdir refuses if anything unexpected
#   is left behind).
#
# Usage:
#   bundle exec ruby quick_start_example.rb              # translate-only demo
#   bundle exec ruby quick_start_example.rb --with-speak # add speak transform

require "tmpdir"

with_speak = ARGV.include?("--with-speak")

CONFIG_FILES        = %w[.reline-dialog-transform.rb .irbrc].freeze
IRB_RUNTIME_FILES   = %w[.irb_history .irb-cache .reline_history].freeze

# --- pre-flight: bundle must have apple_sdk_mac + translation_mac-locale.
#     The user's TAB-doesn't-complete confusion is almost always caused by
#     running this from a bundle that doesn't ship apple_sdk_mac, so fail
#     loud and tell them how to fix it.
def check_loadable(label, path)
  require path
  true
rescue LoadError
  warn ""
  warn "[quick-start] ERROR: #{label} is not in the active bundle."
  warn "[quick-start]        This example needs both apple_sdk_mac and"
  warn "[quick-start]        translation_mac-locale to be loadable."
  warn ""
  warn "[quick-start] Fix: run from the rb-apple-sdk-mac bundle, e.g."
  warn "[quick-start]   cd ../rb-apple-sdk-mac"
  warn "[quick-start]   bundle exec ruby ../reline-dialog-transform/quick_start_example.rb #{ARGV.join(' ')}".strip
  warn ""
  exit 1
end

check_loadable("apple_sdk_mac",          "apple_sdk_mac")
check_loadable("translation_mac-locale", "translation_mac/locale")

scratch = Dir.mktmpdir("reline-dialog-transform-quickstart-")

dotfile_body = +<<~CONF
  # Auto-generated by quick_start_example.rb
  default_lang :ja
  translate
CONF
dotfile_body << "speak voice: \"ja-JP\", rate: 0.5\n" if with_speak

File.write(File.join(scratch, ".reline-dialog-transform.rb"), dotfile_body)

File.write(File.join(scratch, ".irbrc"), <<~IRBRC)
  # Auto-generated by quick_start_example.rb
  $stderr.puts "[quick-start] loading apple_sdk_mac/irb..."
  require "apple_sdk_mac"
  require "apple_sdk_mac/irb"
  AppleSDKMac::IRB.install!
  $stderr.puts "[quick-start] ready. TAB×2 on `Apple::Foundation::URL.app` should show Japanese."
IRBRC

real_cache = ENV["XDG_CACHE_HOME"] || File.expand_path("~/.cache")

speak_note =
  if with_speak
    "  (--with-speak: also speaks via AVSpeechSynthesizer; RELINE_SPEAK=1 will be set)"
  else
    "  (run with --with-speak to additionally speak via AVSpeechSynthesizer)"
  end

puts <<~BANNER
  ============================================================
  reline-dialog-transform quick-start
  ============================================================
  起動する irb 設定:
      default_lang :ja
      translate                # translation_mac-locale 経由
                               # (en → ja, Apple Translation framework)
  #{with_speak ? "      speak    voice: \"ja-JP\"  # AVSpeechSynthesizer (RELINE_SPEAK=1)" : "      # speak は --with-speak 指定時のみ追加"}

  ── やってみるコマンド ──
    1. プロンプトで `Apple::Foundation::URL.app` と打つ (Enter は押さん)
    2. TAB を 1 回押す → 候補 popup が左下に出る
    3. TAB をもう 1 回押す → 右側に doc preview (日本語) が出る
       例: "パスコンポーネントを URL に追加すると…"
    4. `exit` で終了 → quick-start が temp HOME を個別 rm + rmdir

  ── speak 切り替え ──
  #{speak_note}

  ============================================================
  HOME 隔離: #{scratch}
  KB cache:  #{real_cache}
  ============================================================
BANNER

env = {
  "HOME"           => scratch,
  "XDG_CACHE_HOME" => real_cache,
  "TERM"           => ENV["TERM"] || "xterm-256color",
}
env["RELINE_SPEAK"] = "1" if with_speak

system(env, "bundle", "exec", "irb")

# --- cleanup, file-by-file ---
puts
puts "[quick-start] cleaning up #{scratch} (per-file rm + rmdir)..."

CONFIG_FILES.each do |name|
  path = File.join(scratch, name)
  begin
    File.delete(path)
    puts "[quick-start]   removed #{name}"
  rescue Errno::ENOENT
    puts "[quick-start]   missing (skip) #{name}"
  end
end

IRB_RUNTIME_FILES.each do |name|
  path = File.join(scratch, name)
  next unless File.exist?(path)
  File.delete(path)
  puts "[quick-start]   removed irb runtime file #{name}"
end

begin
  Dir.rmdir(scratch)
  puts "[quick-start]   rmdir #{scratch}"
rescue Errno::ENOTEMPTY
  warn "[quick-start] WARN: #{scratch} not empty after explicit cleanup; leaving in place"
  warn "[quick-start]       leftover entries: #{Dir.children(scratch).inspect}"
  warn "[quick-start]       inspect manually before deleting; this script will NOT rm -rf"
end
