#!/usr/bin/env ruby
# frozen_string_literal: true
#
# Quick-start launcher for reline-dialog-transform.
#
# - Verifies the active bundle has apple_sdk_mac + translation_mac-locale
#   (the demo can't show anything interesting without them) and aborts
#   early with a clear how-to-fix message when either is missing.
# - Generates a temporary isolated HOME with the dotfile + .irbrc so
#   your real ~/.irbrc is never touched.
# - Prints copy-pasteable instructions for what to type at the prompt.
# - Spawns `bundle exec irb` against the scratch HOME.
# - Cleans up the scratch HOME file-by-file with File.delete +
#   Dir.rmdir (no rm -rf, ever; rmdir refuses if anything unexpected
#   is left behind).
#
# Usage:
#   bundle exec ruby quick_start_example.rb              # translate-only demo
#   bundle exec ruby quick_start_example.rb --with-speak # add speak transform

require "tmpdir"

with_speak = ARGV.include?("--with-speak")

CONFIG_FILES        = %w[.reline-dialog-transform.rb .irbrc].freeze
IRB_RUNTIME_FILES   = %w[.irb_history .irb-cache .reline_history].freeze

# --- pre-flight: translate transform needs translation_mac-locale.
#     IRB itself ships :show_doc as RDoc-on-TAB, so reline-dialog-
#     transform's wrap has something to layer on top of without any
#     other gem. Only translation_mac-locale is required here, and
#     only for the translate demo to actually translate.
def check_loadable(label, path)
  require path
  true
rescue LoadError
  warn ""
  warn "[quick-start] ERROR: #{label} is not in the active bundle."
  warn "[quick-start]        This example uses `t.translate`, which needs"
  warn "[quick-start]        translation_mac-locale to be loadable."
  warn ""
  exit 1
end

check_loadable("translation_mac-locale", "translation_mac/locale")

scratch = Dir.mktmpdir("reline-dialog-transform-quickstart-")

dotfile_body = +<<~CONF
  # Auto-generated by quick_start_example.rb
  Reline::DialogTransform.install!(default_lang: :ja) do |t|
    # SKIP_RDOC_NON_PROSE skips method signatures, code examples, the
    # IRB header, and RDoc heading rules — only paragraph prose hits
    # Apple Translation. Cuts dialog wait roughly 3x on typical content.
    t.translate skip_if: Reline::DialogTransform::Translate::SKIP_RDOC_NON_PROSE
CONF
dotfile_body << "  t.speak voice: \"ja-JP\", rate: 0.5\n" if with_speak
dotfile_body << "end\n"

File.write(File.join(scratch, ".reline-dialog-transform.rb"), dotfile_body)

File.write(File.join(scratch, ".irbrc"), <<~IRBRC)
  # Auto-generated by quick_start_example.rb
  # IRB registers its own :show_doc dialog (RDoc) when autocomplete is
  # active. require "reline/dialog_transform" auto-loads the dotfile in
  # this same HOME and wraps that :show_doc proc.
  require "reline/dialog_transform"
  $stderr.puts "[quick-start] ready. TAB on a stdlib method should show Japanese."
IRBRC

speak_note =
  if with_speak
    "  (--with-speak: also speaks via AVSpeechSynthesizer; RELINE_SPEAK=1 will be set)"
  else
    "  (run with --with-speak to additionally speak via AVSpeechSynthesizer)"
  end

puts <<~BANNER
  ============================================================
  reline-dialog-transform quick-start
  ============================================================
  起動する irb 設定:
      Reline::DialogTransform.install!(default_lang: :ja) do |t|
        t.translate skip_if: Reline::DialogTransform::Translate::SKIP_RDOC_NON_PROSE
        # ↑ method signature / code example / IRB header / heading は
        #   翻訳しない (Apple Translation 1 行 ~2s で重いため).
        #   prose 段落のみ和訳.
  #{with_speak ? "    t.speak voice: \"ja-JP\"  # AVSpeechSynthesizer (RELINE_SPEAK=1)" : "    # t.speak は --with-speak 指定時のみ追加"}
      end

  ── やってみるコマンド ──
    1. プロンプトで `"hello".ups` と打つ (Enter は押さん)
    2. TAB を押す → 補完候補 (upcase / upcase!) が出て、 highlighted 候補
       に対する show_doc dialog が右側に開く
       例: "すべての小文字が置き換えられた str のコピーを返します..."
    3. ↓ で別候補に移動するとそのメソッドの doc に切り替わる
    4. `exit` で終了 → quick-start が temp HOME を個別 rm + rmdir

  ── speak 切り替え ──
  #{speak_note}

  ============================================================
  HOME 隔離: #{scratch}
  ============================================================
BANNER

env = {
  "HOME" => scratch,
  "TERM" => ENV["TERM"] || "xterm-256color",
}
env["RELINE_SPEAK"] = "1" if with_speak

begin
  system(env, "bundle", "exec", "irb")
rescue Interrupt
  # Ctrl+C inside the spawned irb propagates SIGINT to the whole
  # process group, so the parent receives it as Interrupt. We don't
  # want a stack trace — just fall through to cleanup quietly.
ensure
  puts
  puts "[quick-start] cleaning up #{scratch} (per-file rm + rmdir)..."

  CONFIG_FILES.each do |name|
    path = File.join(scratch, name)
    begin
      File.delete(path)
      puts "[quick-start]   removed #{name}"
    rescue Errno::ENOENT
      puts "[quick-start]   missing (skip) #{name}"
    end
  end

  IRB_RUNTIME_FILES.each do |name|
    path = File.join(scratch, name)
    next unless File.exist?(path)
    File.delete(path)
    puts "[quick-start]   removed irb runtime file #{name}"
  end

  begin
    Dir.rmdir(scratch)
    puts "[quick-start]   rmdir #{scratch}"
  rescue Errno::ENOTEMPTY
    warn "[quick-start] WARN: #{scratch} not empty after explicit cleanup; leaving in place"
    warn "[quick-start]       leftover entries: #{Dir.children(scratch).inspect}"
    warn "[quick-start]       inspect manually before deleting; this script will NOT rm -rf"
  end
end
