#!/usr/bin/env ruby
# frozen_string_literal: true
#
# Quick-start launcher: configures reline-dialog-transform via a
# temporary isolated HOME, spawns `bundle exec irb`, and tells the
# user exactly what to type to see translation in action.
#
# Run from a bundle that has reline-dialog-transform + (optionally)
# apple_sdk_mac + translation_mac-locale path-loaded:
#
#   bundle exec ruby examples/quick_start.rb
#
# When apple_sdk_mac is in the bundle, you'll see Apple SDK doc
# translated; when only translation_mac-locale is there, you'll see
# RDoc translation (pending Ruby 4 RDoc 7.2 Marshal issues).
#
# The temp HOME is removed on exit so your real ~/.irbrc is never
# touched.

require "fileutils"
require "tmpdir"

scratch = Dir.mktmpdir("reline-dialog-transform-quickstart-")

File.write(File.join(scratch, ".reline-dialog-transform.rb"), <<~CONF)
  # Auto-generated by examples/quick_start.rb — translate every
  # dialog line through translation_mac-locale.
  default_lang :ja
  translate

  # Try also: speak alongside translate. Requires apple_sdk_mac
  # for AVSpeechSynthesizer + RELINE_SPEAK=1 to opt in.
  # speak voice: "ja-JP", rate: 0.5
CONF

File.write(File.join(scratch, ".irbrc"), <<~IRBRC)
  # Auto-generated by examples/quick_start.rb
  $stderr.puts "[quick-start] loading reline-dialog-transform..."

  apple_loaded = false
  begin
    require "apple_sdk_mac"
    require "apple_sdk_mac/irb"
    AppleSDKMac::IRB.install!
    apple_loaded = true
    $stderr.puts "[quick-start]   ok: apple_sdk_mac/irb installed"
  rescue LoadError => e
    require "reline/dialog_transform"
    $stderr.puts "[quick-start]   note: apple_sdk_mac not in bundle (\#{e.message})"
    $stderr.puts "[quick-start]         RDoc-only mode; Ruby 4 RDoc may not render :show_doc"
  end

  begin
    require "translation_mac/locale"
    $stderr.puts "[quick-start]   ok: translation_mac/locale available"
  rescue LoadError => e
    $stderr.puts "[quick-start]   warn: translation_mac-locale not in bundle (\#{e.message})"
    $stderr.puts "[quick-start]         translate transform will pass through unchanged"
  end

  $stderr.puts "[quick-start] ready. Hand-off to irb prompt."
IRBRC

real_cache = ENV["XDG_CACHE_HOME"] || File.expand_path("~/.cache")

puts <<~BANNER
  ============================================================
  reline-dialog-transform quick-start
  ============================================================
  起動する irb 設定:
      default_lang :ja
      translate              # translation_mac-locale 経由
                             # (en → ja, Apple Translation framework)

  ── やってみるコマンド ──
    [Apple SDK doc 翻訳のデモ]
      1. プロンプトで `Apple::Foundation::URL.app` と打つ (Enter 押さん)
      2. TAB を 2 回押す
      3. 右側 popup の doc preview が日本語化されてる
         例: "パスコンポーネントを URL に追加すると…"
      ※ 候補絞りたいなら `Apple::Foundation::URL.appendingPathComp`
        まで打って TAB×2

    [挙動確認の小ネタ]
      4. `exit` で irb 終了
      5. 終了したら quick-start が temp HOME を rm -rf する

  ── 動作の前提 (満たさんと translate がパススルーになる) ──
    - bundle に translation_mac-locale が path-loaded されてる
    - apple_sdk_mac が居ると Apple SDK doc 翻訳が見える
       (居らんとき RDoc fallback だけ。 Ruby 4 では :show_doc 死亡)
    - 実機の Apple Translation framework が ja-JP 利用可能
       (TranslationMacHelper helper binary が動く Mac)

  ── speak も試したい時 ──
    .reline-dialog-transform.rb の `# speak voice: ...` コメント外して
    \$ RELINE_SPEAK=1 bundle exec ruby examples/quick_start.rb

  ============================================================
  HOME 隔離: #{scratch}
  KB cache:  #{real_cache}
  ============================================================
BANNER
puts
puts "Press Enter to launch irb..."
$stdin.gets

system({
  "HOME"           => scratch,
  "XDG_CACHE_HOME" => real_cache,
  "TERM"           => ENV["TERM"] || "xterm-256color",
}, "bundle", "exec", "irb")

FileUtils.rm_rf(scratch)
puts
puts "[quick-start] cleaned up #{scratch}"
